# Generated by Django 4.0.2 on 2022-04-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título do projeto')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição do projeto')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Inicio do Trabalho')),
                ('ended_at', models.DateTimeField(verbose_name='Fim do Trabalho')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='base.projeto')),
            ],
        ),
    ]
